# The URL the site will be built for
base_url = "https://florian-reyes.vercel.app/"

compile_sass = true

build_search_index = true


[markdown]
highlight_code = true
highlight_theme = "bbedit"



[extra]

